pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ubermench112/myapp.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Installing Python dependencies...'
                sh '''
                python -m venv venv
                source venv/bin/activate || venv\\Scripts\\activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                sh '''
                source venv/bin/activate || venv\\Scripts\\activate
                pytest || echo "No tests found, skipping..."
                '''
            }
        }

        stage('Docker Build') {
            steps {
                echo 'Building Docker image...'
                sh 'docker build -t myapp .'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the application in Docker...'
                // Stop old container if running
                sh 'docker stop myapp-container || true && docker rm myapp-container || true'
                // Run new container
                sh 'docker run -d -p 5000:5000 --name myapp-container myapp'
            }
        }
    }
}

