pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ubermench112/myapp.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t myapp:${BUILD_NUMBER} -t myapp:latest .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                script {
                    // Stop and remove old container if running
                    sh 'docker ps -q --filter "name=myapp" | grep -q . && docker stop myapp && docker rm myapp || echo "No existing container"'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh 'docker run -d --name myapp -p 8080:8080 myapp:latest'
                }
            }
        }
    }

    post {
        success {
            echo 'Build & Deployment Successful 🎉'
        }
        failure {
            echo 'Build Failed ❌'
        }
    }
}
